[package]
name = "ultimate_project_manager"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.4"
serde = { version = "1.0.197", features = ["derive"] }
toml = "0.8.12"
